# Generated by Django 3.2.8 on 2021-10-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.JSONField(choices=[('Pizzas', 'Pizzas'), ('Salads', 'Salads'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], default='Pizzas', null=True),
        ),
    ]
