# Generated by Django 3.2.8 on 2021-10-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211012_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
