# Generated by Django 3.2.8 on 2021-10-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.JSONField(null=True),
        ),
    ]
